name: CI/CD Deploy AWS 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v3
    - name: Build the Database image
      run: docker build ./database --file Dockerfile --tag titanpxp/databasemysql:2.0

    - uses: docker/build-push-action@v3
    - name: Build the backend image
      run: docker build ./backend --file Dockerfile --tag titanpxp/backend:2.0

    - uses: docker/build-push-action@v3
    - name: Build the frontend image
      run: docker build l/public --file Dockerfile --tag titanpxp/frontend-application:2.0
  push:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v3
    - name: Build the Database image
      run: docker image push titanpxp/databasemysql:2.0
    
    - uses: docker/build-push-action@v3
    - name: Build the Database image
      run: docker image push titanpxp/backend:2.0

    - uses: docker/build-push-action@v3
    - name: Build the Database image
      run: docker image push titanpxp/frontend-application:2.0