name: CI/CD Deploy AWS 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Login-DockerHub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  Build-images:

    runs-on: ubuntu-latest
    needs: Login-DockerHub

    steps:

    - uses: actions/checkout@v3
    
    - name: Build the Database image
      working-directory: database
      run: docker build . --file Dockerfile --tag titanpxp/databasemysql:$(date +%s)
      
    - uses: actions/checkout@v3
    - name: Build the backend image
      working-directory: backend
      run: docker build . --file Dockerfile --tag titanpxp/backend:$(date +%s)

    - uses: actions/checkout@v3
    - name: Build the frontend image
      working-directory: public
      run: docker build . --file Dockerfile --tag titanpxp/frontend-application:$(date +%s)


  Push-Repository:

    runs-on: ubuntu-latest
    needs: Build-images

    steps:
    - uses: actions/checkout@v3
    - name: Build the Database image
      run: docker image push titanpxp/databasemysql:$(date +%s)
    
    - uses: actions/checkout@v3
    - name: Build the Database image
      run: docker image push titanpxp/backend:$(date +%s)

    - uses: actions/checkout@v3
    - name: Build the Database image
      run: docker image push titanpxp/frontend-application:$(date +%s)

